#!/bin/bash -eu

# re-enable preload
if [ -e "${IMAGE_DIR}/etc/ld.so.preload.disabled" ]
then
   mv "${IMAGE_DIR}/etc/ld.so.preload.disabled" "${IMAGE_DIR}/etc/ld.so.preload" 
fi

# unmount the image
print_header "Unmounting the ${IMAGE_NAME} image..."

print_msg "Sync and sleep..."
sync
sleep 3

print_msg "Unmount paritions and sleep..."
umount -l image/boot
umount -l image
sleep 3

